import appealSubmittedCaseDataES from '../appeal-submitted-es';

export default {
  'total': 1,
  cases: [
    {
      ...appealSubmittedCaseDataES.cases[0],
      "id": 37,
      "case_data": {
        ...appealSubmittedCaseDataES.cases[0].case_data,
        'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
      }
    }
  ]
};
