import appealSubmittedCaseData from '../appeal-submitted';

export default {
  ...appealSubmittedCaseData,
  'id': 37,
  'case_data': {
    ...appealSubmittedCaseData.case_data,
    'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
  }
};
