import awaitingReasonsForAppealCaseDataES from '../awaiting-reasons-for-appeal-es';

export default {
  'total': 1,
  cases: [
    {
      ...awaitingReasonsForAppealCaseDataES.cases[0],
      "id": 41,
      "case_data": {
        ...awaitingReasonsForAppealCaseDataES.cases[0].case_data,
        'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
      }
    }
  ]
};
