import awaitingReasonsForAppealCaseData from '../awaiting-reasons-for-appeal';

export default {
  ...awaitingReasonsForAppealCaseData,
  'id': 41,
  'case_data': {
    ...awaitingReasonsForAppealCaseData.case_data,
    'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
  }

};
