import clarifyingQuestionsCaseDataES from '../clarifying-questions-es';

export default {
  'total': 1,
  cases: [
    {
      ...clarifyingQuestionsCaseDataES.cases[0],
      'id': 51,
      'case_data': {
        ...clarifyingQuestionsCaseDataES.cases[0].case_data,
        'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
      }
    }
  ]
};
