import clarifyingQuestionsCaseData from '../clarifying-questions';

export default {
  ...clarifyingQuestionsCaseData,
  'id': 51,
  'case_data': {
    ...clarifyingQuestionsCaseData.case_data,
    'stf24wPreviousStatusWasYesAutoGenerated': 'Yes'
  }

};
