infrastructure_env  = "preprod"
additional_hostname = "ia-aip-frontend3.nonprod.platform.hmcts.net"
idam_url = "http://idam-api.aat.platform.hmcts.net"
idam_web_url = "https://idam-web-public.aat.platform.hmcts.net"
ccd_api_url = "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
s2s_microservice_name = "sscs"
s2s_url = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
